import Head from 'next/head';

/* Major Components */
import { HomePage } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='font-primary'>
        <HomePage/>
      </main>
    </>
  )
}
